GTA5Path=C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V Enhanced\GTA5_Enhanced.exe
EnableOverlay=true
LockOverlay=false
OverlayX=458
OverlayY=14
Language=ru
ShowWidget_Peers=true
ShowWidget_Fps=true
ShowWidget_Ping=true
ShowWidget_Cpu=true
ShowWidget_Ram=true
ShowWidget_Gpu=true
